#pragma once

#include "base/types.h"

enum WlIface : u16 {
  IF_NONE = 0,
  IF_DISPLAY, IF_REGISTRY, IF_CALLBACK, IF_COMPOSITOR, IF_SURFACE, IF_SHM, IF_SHM_POOL, IF_BUFFER,
  IF_SEAT, IF_POINTER, IF_KEYBOARD, IF_OUTPUT,
  IF_XDG_WM_BASE, IF_XDG_SURFACE, IF_XDG_TOPLEVEL,
  IF_FRACTIONAL_MGR, IF_FRACTIONAL, IF_VIEWPORTER, IF_VIEWPORT,
  IF_CURSOR_SHAPE_MGR, IF_CURSOR_SHAPE_DEVICE,
  IF_DATA_DEVICE_MGR, IF_DATA_DEVICE, IF_DATA_SOURCE, IF_DATA_OFFER,
  IF_COUNT
};

enum {
  WL_VER_COMPOSITOR = 6, WL_VER_SHM = 1, WL_VER_SEAT = 9, WL_VER_OUTPUT = 4,
  WL_VER_XDG_WM_BASE = 6, WL_VER_FRACTIONAL = 1, WL_VER_VIEWPORTER = 1, WL_VER_CURSOR_SHAPE = 1,
  WL_VER_DATA_DEVICE_MGR = 3,
};

enum { WL_DISPLAY_SYNC = 0, WL_DISPLAY_GET_REGISTRY = 1 };
enum { WL_DISPLAY_EV_ERROR = 0, WL_DISPLAY_EV_DELETE_ID = 1 };

enum { WL_REGISTRY_BIND = 0 };
enum { WL_REGISTRY_EV_GLOBAL = 0, WL_REGISTRY_EV_GLOBAL_REMOVE = 1 };

enum { WL_CALLBACK_EV_DONE = 0 };

enum { WL_COMPOSITOR_CREATE_SURFACE = 0, WL_COMPOSITOR_CREATE_REGION = 1 };

enum {
  WL_SURFACE_DESTROY = 0, WL_SURFACE_ATTACH = 1, WL_SURFACE_DAMAGE = 2, WL_SURFACE_FRAME = 3,
  WL_SURFACE_SET_OPAQUE_REGION = 4, WL_SURFACE_SET_INPUT_REGION = 5, WL_SURFACE_COMMIT = 6,
  WL_SURFACE_SET_BUFFER_TRANSFORM = 7, WL_SURFACE_SET_BUFFER_SCALE = 8, WL_SURFACE_DAMAGE_BUFFER = 9,
  WL_SURFACE_OFFSET = 10,
};
enum { WL_SURFACE_EV_ENTER = 0, WL_SURFACE_EV_LEAVE = 1, WL_SURFACE_EV_PREFERRED_BUFFER_SCALE = 2,
       WL_SURFACE_EV_PREFERRED_BUFFER_TRANSFORM = 3 };

enum { WL_SHM_CREATE_POOL = 0 };
enum { WL_SHM_EV_FORMAT = 0 };
enum { WL_SHM_FORMAT_ARGB8888 = 0, WL_SHM_FORMAT_XRGB8888 = 1 };
enum { WL_SHM_POOL_CREATE_BUFFER = 0, WL_SHM_POOL_DESTROY = 1, WL_SHM_POOL_RESIZE = 2 };
enum { WL_BUFFER_DESTROY = 0 };
enum { WL_BUFFER_EV_RELEASE = 0 };

enum { WL_SEAT_GET_POINTER = 0, WL_SEAT_GET_KEYBOARD = 1, WL_SEAT_GET_TOUCH = 2, WL_SEAT_RELEASE = 3 };
enum { WL_SEAT_EV_CAPABILITIES = 0, WL_SEAT_EV_NAME = 1 };
enum { WL_SEAT_CAP_POINTER = 1, WL_SEAT_CAP_KEYBOARD = 2, WL_SEAT_CAP_TOUCH = 4 };

enum { WL_POINTER_SET_CURSOR = 0, WL_POINTER_RELEASE = 1 };
enum {
  WL_POINTER_EV_ENTER = 0, WL_POINTER_EV_LEAVE = 1, WL_POINTER_EV_MOTION = 2, WL_POINTER_EV_BUTTON = 3,
  WL_POINTER_EV_AXIS = 4, WL_POINTER_EV_FRAME = 5, WL_POINTER_EV_AXIS_SOURCE = 6, WL_POINTER_EV_AXIS_STOP = 7,
  WL_POINTER_EV_AXIS_DISCRETE = 8, WL_POINTER_EV_AXIS_VALUE120 = 9, WL_POINTER_EV_AXIS_RELATIVE_DIRECTION = 10,
};
enum { WL_POINTER_AXIS_VERTICAL = 0, WL_POINTER_AXIS_HORIZONTAL = 1 };

enum { WL_KEYBOARD_RELEASE = 0 };
enum { WL_KEYBOARD_EV_KEYMAP = 0, WL_KEYBOARD_EV_ENTER = 1, WL_KEYBOARD_EV_LEAVE = 2, WL_KEYBOARD_EV_KEY = 3,
       WL_KEYBOARD_EV_MODIFIERS = 4, WL_KEYBOARD_EV_REPEAT_INFO = 5 };
enum { WL_KEYBOARD_KEYMAP_XKB_V1 = 1 };

enum { WL_OUTPUT_RELEASE = 0 };
enum { WL_OUTPUT_EV_GEOMETRY = 0, WL_OUTPUT_EV_MODE = 1, WL_OUTPUT_EV_DONE = 2, WL_OUTPUT_EV_SCALE = 3,
       WL_OUTPUT_EV_NAME = 4, WL_OUTPUT_EV_DESCRIPTION = 5 };

enum { XDG_WM_BASE_DESTROY = 0, XDG_WM_BASE_CREATE_POSITIONER = 1, XDG_WM_BASE_GET_XDG_SURFACE = 2, XDG_WM_BASE_PONG = 3 };
enum { XDG_WM_BASE_EV_PING = 0 };
enum { XDG_SURFACE_DESTROY = 0, XDG_SURFACE_GET_TOPLEVEL = 1, XDG_SURFACE_GET_POPUP = 2,
       XDG_SURFACE_SET_WINDOW_GEOMETRY = 3, XDG_SURFACE_ACK_CONFIGURE = 4 };
enum { XDG_SURFACE_EV_CONFIGURE = 0 };
enum {
  XDG_TOPLEVEL_DESTROY = 0, XDG_TOPLEVEL_SET_PARENT = 1, XDG_TOPLEVEL_SET_TITLE = 2, XDG_TOPLEVEL_SET_APP_ID = 3,
  XDG_TOPLEVEL_SHOW_WINDOW_MENU = 4, XDG_TOPLEVEL_MOVE = 5, XDG_TOPLEVEL_RESIZE = 6, XDG_TOPLEVEL_SET_MAX_SIZE = 7,
  XDG_TOPLEVEL_SET_MIN_SIZE = 8, XDG_TOPLEVEL_SET_MAXIMIZED = 9, XDG_TOPLEVEL_UNSET_MAXIMIZED = 10,
  XDG_TOPLEVEL_SET_FULLSCREEN = 11, XDG_TOPLEVEL_UNSET_FULLSCREEN = 12, XDG_TOPLEVEL_SET_MINIMIZED = 13,
};
enum { XDG_TOPLEVEL_EV_CONFIGURE = 0, XDG_TOPLEVEL_EV_CLOSE = 1, XDG_TOPLEVEL_EV_CONFIGURE_BOUNDS = 2,
       XDG_TOPLEVEL_EV_WM_CAPABILITIES = 3 };
enum { XDG_TOPLEVEL_STATE_MAXIMIZED = 1, XDG_TOPLEVEL_STATE_FULLSCREEN = 2, XDG_TOPLEVEL_STATE_RESIZING = 3,
       XDG_TOPLEVEL_STATE_ACTIVATED = 4 };

enum { WL_DATA_DEVICE_MGR_CREATE_DATA_SOURCE = 0, WL_DATA_DEVICE_MGR_GET_DATA_DEVICE = 1 };
enum { WL_DATA_DEVICE_START_DRAG = 0, WL_DATA_DEVICE_SET_SELECTION = 1, WL_DATA_DEVICE_RELEASE = 2 };
enum { WL_DATA_DEVICE_EV_DATA_OFFER = 0, WL_DATA_DEVICE_EV_ENTER = 1, WL_DATA_DEVICE_EV_LEAVE = 2, WL_DATA_DEVICE_EV_MOTION = 3,
       WL_DATA_DEVICE_EV_DROP = 4, WL_DATA_DEVICE_EV_SELECTION = 5 };
enum { WL_DATA_SOURCE_OFFER = 0, WL_DATA_SOURCE_DESTROY = 1, WL_DATA_SOURCE_SET_ACTIONS = 2 };
enum { WL_DATA_SOURCE_EV_TARGET = 0, WL_DATA_SOURCE_EV_SEND = 1, WL_DATA_SOURCE_EV_CANCELLED = 2,
       WL_DATA_SOURCE_EV_DND_DROP_PERFORMED = 3, WL_DATA_SOURCE_EV_DND_FINISHED = 4, WL_DATA_SOURCE_EV_ACTION = 5 };
enum { WL_DATA_OFFER_ACCEPT = 0, WL_DATA_OFFER_RECEIVE = 1, WL_DATA_OFFER_DESTROY = 2, WL_DATA_OFFER_FINISH = 3, WL_DATA_OFFER_SET_ACTIONS = 4 };
enum { WL_DATA_OFFER_EV_OFFER = 0, WL_DATA_OFFER_EV_SOURCE_ACTIONS = 1, WL_DATA_OFFER_EV_ACTION = 2 };

enum { WP_FRACTIONAL_MGR_DESTROY = 0, WP_FRACTIONAL_MGR_GET_FRACTIONAL_SCALE = 1 };
enum { WP_FRACTIONAL_DESTROY = 0 };
enum { WP_FRACTIONAL_EV_PREFERRED_SCALE = 0 }; // scale in 120ths

enum { WP_VIEWPORTER_DESTROY = 0, WP_VIEWPORTER_GET_VIEWPORT = 1 };
enum { WP_VIEWPORT_DESTROY = 0, WP_VIEWPORT_SET_SOURCE = 1, WP_VIEWPORT_SET_DESTINATION = 2 };

enum { WP_CURSOR_SHAPE_MGR_DESTROY = 0, WP_CURSOR_SHAPE_MGR_GET_POINTER = 1 };
enum { WP_CURSOR_SHAPE_DEVICE_DESTROY = 0, WP_CURSOR_SHAPE_DEVICE_SET_SHAPE = 1 };
enum CursorShape : u32 {
  CURSOR_DEFAULT = 1, CURSOR_CONTEXT_MENU = 2, CURSOR_HELP = 3, CURSOR_POINTER = 4, CURSOR_PROGRESS = 5,
  CURSOR_WAIT = 6, CURSOR_CELL = 7, CURSOR_CROSSHAIR = 8, CURSOR_TEXT = 9, CURSOR_VERTICAL_TEXT = 10,
  CURSOR_ALIAS = 11, CURSOR_COPY = 12, CURSOR_MOVE = 13, CURSOR_NO_DROP = 14, CURSOR_NOT_ALLOWED = 15,
  CURSOR_GRAB = 16, CURSOR_GRABBING = 17, CURSOR_E_RESIZE = 18, CURSOR_N_RESIZE = 19, CURSOR_NE_RESIZE = 20,
  CURSOR_NW_RESIZE = 21, CURSOR_S_RESIZE = 22, CURSOR_SE_RESIZE = 23, CURSOR_SW_RESIZE = 24, CURSOR_W_RESIZE = 25,
  CURSOR_EW_RESIZE = 26, CURSOR_NS_RESIZE = 27, CURSOR_NESW_RESIZE = 28, CURSOR_NWSE_RESIZE = 29,
  CURSOR_COL_RESIZE = 30, CURSOR_ROW_RESIZE = 31, CURSOR_ALL_SCROLL = 32, CURSOR_ZOOM_IN = 33, CURSOR_ZOOM_OUT = 34,
};
